---
- name: Install Node.js
  hosts: webapp
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes 
    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

- name: Create new user for nodejs app
  hosts: webapp
  become: yes
  tasks:
    - name: Create devops user
      user:
        name: devops
        comment: "User for running nodejs app"
        groups: sudo
        append: yes
        create_home: yes
        shell: /bin/bash
    
- name: Deploy nodejs app
  hosts: webapp
  become: true
  become_user: devops      
  tasks:
    - name: Extract nodejs app
      unarchive:
        src: /Users/mac/devop-project/nodejs-web-app/simple-web-app-1.0.0.tgz
        dest: /home/devops/
    - name: Install app dependencies
      npm:
        path: /home/devops/package
    - name: Start nodejs app
      command:
        chdir: /home/devops/package
        cmd: node server.js
      async: 1000
      poll: 0
    - name: Ensure nodejs app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{ app_status.stdout}}

