---
- name: Install Node.js
  hosts: webapp
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes 
    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

- name: Create new user for nodejs app
  hosts: webapp
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Create devops user
      user:
        name: "{{app_user}}"
        comment: "User for running nodejs app"
        groups: sudo
        append: yes
        create_home: yes
        shell: /bin/bash
    
- name: Deploy nodejs app
  hosts: webapp
  become: yes
  vars_files:
    - vars.yaml     
  tasks:
    - name: Extract nodejs app
      unarchive:
        src: "{{location}}/simple-web-app-{{version}}.tgz"
        dest: "{{user_home_dir}}"
    - name: Install app dependencies
      npm:
        path: "{{user_home_dir}}/package"
    - name: Start nodejs app
      command:
        chdir: "{{user_home_dir}}/package"
        cmd: node server.js
      async: 1000
      poll: 0
    - name: Ensure nodejs app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{ app_status.stdout}}

