---
- name: Configure nginx web server
  hosts: webserver
  become: yes

  tasks:
    - name: uninstall nginx
      apt:
        name: nginx
        state: absent

    - name: Stopt nginx service
      service:
        name: nginx
        state: stopped
        enabled: yes

    - name: Create index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Welcome to the Nginx Web Server!</h1>"